flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_blog/main/views.py
from flask import render_template, Blueprint

from flask_blog.models import User

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/index")
def index():
    return render_template('index.html')

flask_blog/posts/views.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post, User
from flask_blog.posts.forms import PostForm
from flask_blog.users.views import users

posts = Blueprint('posts', __name__)


@posts.route('/allpost')
@login_required
def all_post():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('all_post.html', posts=posts)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.all_post'))
    return render_template('create_post.html',
                           title='Новый пост', form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста',
                           form=form, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST', 'GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.all_post'))

flask_blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm, UpdateUserForm, RequestResetForm, ResetPasswordForm)

from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password1.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись успешно создана!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.all_post'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('posts.all_post'))
        else:
            flash('Неверные данные для входа', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=
                                    form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' +
                                            current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, posts=posts,
                           user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.all_posts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.all_post'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.\
            generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! '
              'Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Сброс пароля', form=form)

flask_blog/templates/account.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2>Редактирование профиля - {{ current_user.username }}</h2>
        </div>
      </div>
      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Аккаунт пользователя</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   



{% endblock content %}

flask_blog/templates/all_post.html
{% extends "base.html" %}

{% block content %}
{% for post in posts.items %}
<a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto;">{{
    post.author.username }}</a>
<h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
<small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
<br>
<br>
<p class="card-text">{{ post.content }}</p>
<div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px;"
             src="{{ url_for('static',
 filename='profile_pics/' + post.author.image_file) }}">
    </article>
</div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-success mb-4" href="{{ url_for('posts.all_post', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-success mb-4" href="{{ url_for('posts.all_post', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% endif %}
{% endfor %}
{% endblock content %}

flask_blog/templates/base.html
<!DOCTYPE HTML>
<html>
{% block head %}
<head>
    <title>{{ title }}</title>
    <meta name="description" content="website description"/>
    <meta name="keywords" content="website keywords, website keywords"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/style.css') }}">
</head>
{% endblock %}
<body>
<div id="main">
    <div id="header">
        <div id="logo">
            <div id="logo_text">
                <h1>Мой блог!</h1>
                <h2>Привет!</h2>
            </div>
        </div>
        <div id="menubar">
            <ul id="menu">
                <li class="selected">
                    <a href="{{url_for('main.index') }}">Главная</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="selected">
                    <a href="{{ url_for('users.account') }}"><i class="fa fa-user"></i>Профиль</a>
                    <a href="{{ url_for('posts.all_post') }}"><i class="fa fa-user"></i>Посты</a>
                    <a href="{{ url_for('posts.new_post') }}"><i class="fa fa-user"></i>Новый пост +</a>
                    <a href="{{ url_for('users.logout') }}"><i class="fa fa-user"></i>Выйти</a>
                </li>
                {% else %}
                <li class="selected">
                    <a href="{{url_for('users.register') }}">Зарегистрироваться</a>
                    <a href="{{url_for('users.login') }}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="site_content">
        <div class="sidebar">
            <h3>Последние записи блога</h3>
            <h4>Блог создан</h4>
            <h5>17 июня 2022 года</h5>
            <p>Здесь размещена карточка-заготовка для дальнейших записей<br/><a
                    href="#">Читать дальше</a></p>
            <p></p>
            <h3>Искать</h3>
            <form method="post" action="#" id="search_form">
                <p>
                    <input class="search" type="text" name="search_field" value="Введите запрос..."/>
                    <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;"
                           src="../static/styles/search.png"
                           alt="Search" title="Search"/>
                </p>
            </form>
        </div>

        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <div id="footer">
        Copyright &copy; Александр Болотов | <a href="https://github.com/alexabolot1">GitHub</a> | <a
            href="https://vk.com/alexabolot">VK</a> | <a
            href="https://t.me/alexabolot">Telegram</a>
    </div>
</div>
</body>
</html>

flask_blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <form method="POST" action="">
        <div class="form_settings">
        {{ form.hidden_tag() }}
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <br>
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

{% endblock content %}

flask_blog/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Добро пожаловать в мой блог!</h1>
<p>Пока здесь ничего не будет, но скоро появится :)</p>
{% endblock %}

flask_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Авторизация</h1>
<form method="POST" action="#">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-check">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-label") }}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
    <small style="font-size: 15px; font-weight: 500;">
        Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
    </small>
    <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
    </small>
</form>
{% endblock %}

flask_blog/templates/post.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <article class="media" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px;"
             src="{{ url_for('static', filename='profile_pics/' +
		post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts',
		username=post.author.username) }}" style="margin: 0
	auto">{{ post.author.username }}</a>
    </article>
    <h4 class="card-title">{{ post.title }}</h4>
    <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
    <br>
    <br>
    <p>{{ post.content }}</p>
    {% if post.author == current_user %}
    <a href="{{ url_for('posts.update_post', post_id=post.id) }}">Редактировать</a>
    <br>
    <br>
    <a href="{{ url_for('posts.delete_post', post_id=post.id) }}">Удалить</a>
    {% endif %}
</div>
{% endblock content %}

flask_blog/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Регистрация</h1>
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password1.label(class="form-control-label") }}
            {% if form.password1.errors %}
            {{ form.password1(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password1.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.password1(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password2.label(class="form-control-label") }}
            {% if form.password2.errors %}
            {{ form.password2(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password2.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.password2(class="form-control form-control-lg") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
{% endblock %}

flask_blog/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Сброс пароля</legend>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
{% endblock content %}

flask_blog/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Сброс пароля</legend>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors %}
            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
<h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media" style="display: flex; flex-direction: column;">
    <img class="rounded-circle article-img" style="margin-right: 5px;"
         src="{{ url_for('static', filename='profile_pics/' +
		post.author.image_file) }}">
    <a class="mr-2" href="{{ url_for('users.user_posts',
	username=post.author.username) }}" style="margin: 0 auto">{{
        post.author.username }}</a>
</article>
<br>
<div class="card" style="margin-bottom: 20px;">
    <div class="card-body">
        <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
        </h4>
        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p>{{ post.content }}</p>
    </div>
</div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
{% else %}
<a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}